### ISSUE TITLE
How do I upgrade to this? 

### ISSUE THREAD

**Issue by johntdyer** [home-assistant-snap/zwavejs2mqtt#1]
Seems I am running an older version... I'm new to snap so maybe I'm not trying to upgrade correctly?

```
15:36:30 jdyer@coruscant.local ~ snap list

Name                    Version    Rev    Tracking       Publisher       Notes
certbot                 1.21.0     1582   latest/stable  certbot-eff✓    classic
certbot-dns-cloudflare  1.21.0     1189   latest/stable  certbot-eff✓    -
core                    16-2.52.1  11993  latest/stable  canonical✓      core
core20                  20211115   1242   latest/stable  canonical✓      base
hello-world             6.4        29     latest/stable  canonical✓      -
zwavejs2mqtt            v5.12.0    262    latest/stable  giaever-online  -
15:36:52 jdyer@coruscant.local ~
```

**Comment by jmgiaever** [comment]
Hi,Which version would you like to upgrade to?

You can read the release information described in `snap info zwavejs2mqtt`. 

But in short `latest/stable` will simply have the latest stable. That would be the last patch of the last release. That is 5.12.0 at the moment. It will update to 6.0.x when version 6.0 have received it's last patch release.

If you want rolling releases, then you should change to `latest/candidate`. This will receive new releases as soon as they are released and I've managed to rebuild it. Normally same day. Currently you'll have 6.0.2 in this channel. 

You can switch with `snap switch zwavejs2mqtt --channel=latest/candidate

**Comment by johntdyer** [comment]
>that is 5.12.0 at the moment. It will update to 6.0.x when version 6.0 have received it's last patch release.

Thank you that was very helpful, might I ask though what you mean by 6.0 getting its last patch release?   Is this some Snap'ism that I am maybe unfamiliar with ?   I see zwwavejq2mqtt is at 6.0.2 upstream

**Comment by jmgiaever** [comment]
Let say that 6.0.2 is the last (patch) release of version 6.0 when the next version upstream becomes 6.1.0. 

When 6.0.2 is the last patch version of version 6.0 - 6.0.2 will then be placed in `latest/stable` and `6.1.0` in `latest/candidate`. 

We only touch the latest/stable once per version. Latest candidate for every release. 

This has nothing to do with snap. It's just a decision I've taken, since snaps are self updating. 

People that don't want frequent updates can choose to be on the stable. It will cause less restarts for example and you're not "on the edge". 

However restarts are not such a big of a deal with zwavejs, as it was with OZW, but restarts can interrupt stuff.

**Comment by jmgiaever** [comment]
All good? I'm closing this. Feel free to re-open :)
